import type { NodeInstance, NodeSpec } from '../../../store/types';

export const mockSpecs: NodeSpec[] = [
  {
    id: 'gaussian_blur',
    display_name: 'Gaussian Blur',
    category: 'Filter',
    description: 'Apply gaussian blur',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'amount',
        label: 'Amount',
        ty: 'Float',
        default: { Float: 0.5 },
        min: 0,
        max: 5,
        step: 0.01,
        ui_hint: { type: 'Slider' },
        promotable: true,
      },
      {
        key: 'radius',
        label: 'Radius',
        ty: 'Float',
        default: { Float: 1.0 },
        min: 0,
        max: 20,
        step: 0.1,
        ui_hint: { type: 'Slider' },
        promotable: true,
      },
    ],
  },
  {
    id: 'viewer',
    display_name: 'Viewer',
    category: 'Output',
    description: 'Displays image',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [],
    params: [],
  },
  {
    id: 'load_image',
    display_name: 'Load Image',
    category: 'Input',
    description: 'Loads an image',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'path',
        label: 'Path',
        ty: 'String',
        default: { String: '' },
        ui_hint: { type: 'FilePicker' },
        promotable: false,
      },
    ],
  },
  {
    id: 'blend',
    display_name: 'Blend',
    category: 'Composite',
    description: 'Blends two images',
    inputs: [
      { name: 'base', label: 'Base', ty: 'Image' },
      { name: 'overlay', label: 'Overlay', ty: 'Image' },
    ],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'mode',
        label: 'Mode',
        ty: 'Int',
        default: { Int: 0 },
        min: 0,
        max: 3,
        step: 1,
        ui_hint: { type: 'Dropdown', data: ['Normal', 'Multiply', 'Screen', 'Overlay'] },
        promotable: false,
      },
      {
        key: 'opacity',
        label: 'Opacity',
        ty: 'Float',
        default: { Float: 1.0 },
        min: 0,
        max: 1,
        step: 0.01,
        ui_hint: { type: 'Slider' },
        promotable: true,
      },
    ],
  },
  {
    id: 'gradient',
    display_name: 'Gradient',
    category: 'Generator',
    description: 'Generates gradient field',
    inputs: [],
    outputs: [{ name: 'field', label: 'Field', ty: 'Field' }],
    params: [
      {
        key: 'direction',
        label: 'Direction',
        ty: 'Int',
        default: { Int: 0 },
        min: 0,
        max: 3,
        step: 1,
        ui_hint: { type: 'Dropdown', data: ['Horizontal', 'Vertical', 'Radial', 'Angular'] },
        promotable: true,
      },
      {
        key: 'start_color',
        label: 'Start Color',
        ty: 'Color',
        default: { Color: [0, 0, 0, 1] },
        ui_hint: { type: 'ColorPicker' },
        promotable: true,
      },
      {
        key: 'end_color',
        label: 'End Color',
        ty: 'Color',
        default: { Color: [1, 1, 1, 1] },
        ui_hint: { type: 'ColorPicker' },
        promotable: true,
      },
    ],
  },
  {
    id: 'solid_color',
    display_name: 'Solid Color',
    category: 'Generator',
    description: 'Generates solid color',
    inputs: [],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'color',
        label: 'Color',
        ty: 'Color',
        default: { Color: [0, 0, 0, 1] },
        ui_hint: { type: 'ColorPicker' },
        promotable: true,
      },
      {
        key: 'width',
        label: 'Width',
        ty: 'Int',
        default: { Int: 512 },
        min: 1,
        max: 4096,
        ui_hint: { type: 'NumberInput' },
        promotable: false,
      },
      {
        key: 'height',
        label: 'Height',
        ty: 'Int',
        default: { Int: 512 },
        min: 1,
        max: 4096,
        ui_hint: { type: 'NumberInput' },
        promotable: false,
      },
    ],
  },
  {
    id: 'resize',
    display_name: 'Resize',
    category: 'Transform',
    description: 'Resizes image',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'width',
        label: 'Width',
        ty: 'Int',
        default: { Int: 512 },
        min: 1,
        max: 8192,
        ui_hint: { type: 'NumberInput' },
        promotable: false,
      },
      {
        key: 'height',
        label: 'Height',
        ty: 'Int',
        default: { Int: 512 },
        min: 1,
        max: 8192,
        ui_hint: { type: 'NumberInput' },
        promotable: false,
      },
    ],
  },
  {
    id: 'threshold',
    display_name: 'Threshold',
    category: 'Color',
    description: 'Applies threshold',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'invert',
        label: 'Invert',
        ty: 'Bool',
        default: { Bool: false },
        ui_hint: { type: 'Checkbox' },
        promotable: true,
      },
    ],
  },
  {
    id: 'color_palette',
    display_name: 'Color Palette',
    category: 'Color',
    description: 'Define a color palette',
    inputs: [],
    outputs: [{ name: 'palette', label: 'Palette', ty: 'Image' }],
    params: [
      {
        key: 'colors',
        label: 'Colors',
        ty: 'Color',
        default: { ColorPalette: [[1, 0, 0, 1], [0, 1, 0, 1], [0, 0, 1, 1]] },
        ui_hint: { type: 'ColorPalette' },
        promotable: false,
      },
    ],
  },
  {
    id: 'color_ramp',
    display_name: 'Color Ramp',
    category: 'Color',
    description: 'Map luminance through a color ramp',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'stops',
        label: 'Color Ramp',
        ty: 'Float',
        default: { ColorRamp: [{ position: 0, color: [0, 0, 0, 1] }, { position: 1, color: [1, 1, 1, 1] }] },
        ui_hint: { type: 'ColorRamp' },
        promotable: true,
      },
    ],
  },
  {
    id: 'curves',
    display_name: 'Curves',
    category: 'Color',
    description: 'Adjust tonal curves',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'master_curve',
        label: 'Master',
        ty: 'Float',
        default: { CurvePoints: [{ x: 0, y: 0 }, { x: 1, y: 1 }] },
        ui_hint: { type: 'CurveEditor' },
        promotable: false,
      },
    ],
  },
  {
    id: 'ai_generate_image',
    display_name: 'AI Generate Image',
    category: 'AI',
    description: 'Generates an image from a text prompt',
    inputs: [{ name: 'prompt', label: 'Prompt', ty: 'String' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'prompt',
        label: 'Prompt',
        ty: 'String',
        default: { String: '' },
        ui_hint: { type: 'TextArea' },
        promotable: true,
      },
      {
        key: 'width',
        label: 'Width',
        ty: 'Int',
        default: { Int: 512 },
        min: 64,
        max: 2048,
        ui_hint: { type: 'NumberInput' },
        promotable: false,
      },
      {
        key: 'height',
        label: 'Height',
        ty: 'Int',
        default: { Int: 512 },
        min: 64,
        max: 2048,
        ui_hint: { type: 'NumberInput' },
        promotable: false,
      },
    ],
  },
  {
    id: 'gpu_kernel::pixelate',
    display_name: 'Pixelate',
    category: 'GPU',
    description: 'Pixelates an image',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'pixel_size',
        label: 'Pixel Size',
        ty: 'Int',
        default: { Int: 8 },
        min: 1,
        max: 128,
        ui_hint: { type: 'Slider' },
        promotable: true,
      },
    ],
  },
  {
    id: 'posterize',
    display_name: 'Posterize',
    category: 'Color',
    description: 'Reduces number of color levels',
    inputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    outputs: [{ name: 'image', label: 'Image', ty: 'Image' }],
    params: [
      {
        key: 'levels',
        label: 'Levels',
        ty: 'Int',
        default: { Int: 4 },
        min: 2,
        max: 256,
        ui_hint: { type: 'Slider' },
        promotable: true,
      },
    ],
  },
  {
    id: 'math',
    display_name: 'Math',
    category: 'Utility',
    description: 'Apply math operations on float values',
    inputs: [
      {
        name: 'a',
        label: 'A',
        ty: 'Float',
        default: { Float: 0 },
        step: 0.01,
        ui_hint: { type: 'NumberInput' },
      },
      {
        name: 'b',
        label: 'B',
        ty: 'Float',
        default: { Float: 0 },
        step: 0.01,
        ui_hint: { type: 'NumberInput' },
      },
    ],
    outputs: [{ name: 'value', label: 'Value', ty: 'Float' }],
    params: [
      {
        key: 'operation',
        label: 'Operation',
        ty: 'Int',
        default: { Int: 0 },
        min: 0,
        max: 13,
        step: 1,
        ui_hint: {
          type: 'Dropdown',
          data: ['Add', 'Subtract', 'Multiply', 'Divide', 'Power', 'Min', 'Max', 'Abs', 'Greater Than', 'Less Than', 'Clamp', 'Step', 'Smooth Step', 'Lerp'],
        },
        promotable: false,
      },
      {
        key: 'clamp_result',
        label: 'Clamp Result',
        ty: 'Bool',
        default: { Bool: false },
        ui_hint: { type: 'Checkbox' },
        promotable: false,
      },
    ],
  },
];

export const makeNodeInstance = (overrides: Partial<NodeInstance> & { id: string; typeId: string }): NodeInstance => ({
  id: overrides.id,
  typeId: overrides.typeId,
  params: overrides.params ?? {},
  inputDefaults: overrides.inputDefaults ?? {},
  position: overrides.position ?? { x: 0, y: 0 },
  muted: overrides.muted ?? false,
});
